# Generated by Django 3.1 on 2022-05-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SowingDate', models.CharField(max_length=20)),
                ('HarvestingDate', models.CharField(max_length=20)),
                ('pesticideRecommendation', models.CharField(max_length=30)),
                ('DataPublished', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Land_size', models.FloatField()),
                ('Wheat_variety', models.CharField(max_length=20)),
                ('Fertilizer_type', models.CharField(max_length=30)),
                ('Fertilizer_amount', models.FloatField()),
                ('Topography', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First', models.CharField(max_length=64)),
                ('Last', models.CharField(max_length=64)),
                ('Email', models.CharField(max_length=128, unique=True)),
                ('Phone', models.IntegerField(unique=True)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
            ],
        ),
    ]
