# Generated by Django 4.0.4 on 2022-05-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daasapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Village',
        ),
    ]
