# Generated by Django 4.0.4 on 2022-05-08 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daasapp', '0002_delete_village'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=64)),
                ('month', models.IntegerField(max_length=64)),
                ('day', models.IntegerField(max_length=128, unique=True)),
                ('tmin', models.DecimalField(decimal_places=2, max_digits=3, unique=True)),
                ('tmax', models.DecimalField(decimal_places=2, max_digits=3, unique=True)),
                ('rain', models.DecimalField(decimal_places=2, max_digits=3, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daasapp.district')),
            ],
        ),
    ]
