# Generated by Django 4.0.4 on 2022-05-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daasapp', '0003_district_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='rain',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='tmax',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='tmin',
            field=models.FloatField(),
        ),
    ]
