# Generated by Django 4.0.4 on 2022-05-08 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daasapp', '0004_alter_weather_rain_alter_weather_tmax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='district',
        ),
    ]
