# Generated by Django 4.0.4 on 2022-05-23 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daasapp', '0005_remove_weather_district'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalyzedData',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Farmer',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
